name: Build Firmware

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install qmk
        run: brew install qmk/qmk/qmk
      - name: Install arm-gcc 10
        run: brew install arm-gcc-bin@10
      - name: Install avr-gcc 8
        run: brew link --force avr-gcc@8
      - name: clone SonixQMK
        run: git clone -b sn32-josh https://github.com/itspriddle/qmk_firmware.git
      - name: pip
        run: cd qmk_firmware && python3 -m pip install -r requirements.txt
      - name: git submodules
        run: cd qmk_firmware && make git-submodule
      - name: compile firmware
        run: cd qmk_firmware && make keychron/k6:ansi-josh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qmk_firmware/keychron_k6_ansi-josh.bin
